In [1]:
import tensorflow as tf

One Dimensional Tensor



In [2]:
onedimvar=tf.constant(4)
print(onedimvar)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
onedimvar=tf.constant([4,1,2,3,4])
onedimvar

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 1, 2, 3, 4], dtype=int32)>

Two Dimensional Tensor

In [4]:
tensor2=tf.constant([
    [1,2,3,4],
    [2,3,4,5],
    [1,2,4,5],
    [7,4,5,5]
])
tensor2

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [1, 2, 4, 5],
       [7, 4, 5, 5]], dtype=int32)>

Three Dimensional Tensor

In [5]:
tensor3=tf.constant([
    [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
     [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
])
tensor3

<tf.Tensor: shape=(4, 2, 4), dtype=int32, numpy=
array([[[1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[1, 2, 4, 5],
        [7, 4, 5, 5]],

       [[1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[1, 2, 4, 5],
        [7, 4, 5, 5]]], dtype=int32)>

In [6]:
tensor4=tf.constant([
    [
    [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
     [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
],
    [
    [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
     [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
],
    [
    [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
     [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
],
    [
    [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
     [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
],
])
tensor4

<tf.Tensor: shape=(4, 4, 2, 4), dtype=int32, numpy=
array([[[[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]],

        [[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]]],


       [[[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]],

        [[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]]],


       [[[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]],

        [[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]]],


       [[[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]],

        [[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]]]], dtype=int32)>

Eye

In [7]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=5,
    batch_shape=None,
    dtype=tf.dtypes.float32
)
eye_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [8]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[5,9],
    dtype=tf.dtypes.float32
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  ...

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  ...

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0.

Fill

In [9]:
fill_tensor=tf.fill(
    [3,3,3,3,3],11,name=None
)
print(fill_tensor)

tf.Tensor(
[[[[[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]]


  [[[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]]


  [[[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]]]



 [[[[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]]


  [[[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]]


  [[[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]]]



 [[[[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
   

One

In [10]:
one_tensor=tf.ones(
    [5,5,15],
    dtype=tf.float32,
    name=None
)
print(one_tensor)

tf.Tensor(
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 

In [11]:
ones_like_tensor=tf.ones_like(fill_tensor,
                              dtype=None,
                              name=None

)
print(ones_like_tensor)

tf.Tensor(
[[[[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]]



 [[[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]]



 [[[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 

Normal

In [12]:
normal_tensor=tf.random.normal(
    [5,5,5],
     mean=0.0,
    stddev=1.0,

    dtype=tf.float32,
    seed=None,
    name=None
)
print(normal_tensor)

tf.Tensor(
[[[ 1.2294166   0.717067   -0.39894384 -1.0389483  -1.170547  ]
  [ 0.34977913 -0.0050879  -2.4139454   1.50332    -1.3440794 ]
  [ 0.36100695 -1.1189206  -0.758419    1.1587923   0.06719146]
  [ 1.9839876  -0.30148947  1.9287853   0.17481804 -1.0367182 ]
  [-1.4391909  -0.08184283  0.31649163 -0.29679576 -0.5699517 ]]

 [[-1.1690314  -0.06285986  2.4414358   1.9322402  -1.3630947 ]
  [-0.69634473  1.2607899   0.36662433 -1.1837257   0.8849497 ]
  [-0.20019662 -0.8015511   0.26232073 -1.5423216  -0.11986133]
  [-0.5371377  -0.589376    0.13128155 -0.71809995 -1.6737349 ]
  [-0.12205825  0.2731576  -1.0520617   1.9925462   0.37753433]]

 [[ 1.302807    0.7136712   2.0887806  -0.41952264  0.04500336]
  [ 2.1938808  -1.7099879  -0.90218985 -1.0825138   0.38677078]
  [-0.6472828  -0.5842908   0.42583638 -1.4327314  -0.70862174]
  [-0.58020014  0.06252498 -1.1741692   1.1953617   0.6843947 ]
  [ 1.2711632   0.51131743 -0.8864238  -0.7371767  -0.41435468]]

 [[ 1.2416434  -0.13858

In [13]:
uniform_tensor=tf.random.uniform(
    [5,5,5],
    minval=0,
    maxval=1000,

    dtype=tf.float32,
    seed=None,
    name=None
)
print(uniform_tensor)

tf.Tensor(
[[[457.70312  447.8128   827.7991   271.129    553.19714 ]
  [957.2481   997.04065  681.50543  624.7252   696.63824 ]
  [543.29254  671.52057   31.040192 232.94865  598.46686 ]
  [656.4088   234.10594  503.83447  485.17072  651.4442  ]
  [  9.557366 519.2956   136.25623  897.4583   140.50114 ]]

 [[247.89917  251.78278  661.21686  590.78564  655.50385 ]
  [ 47.9089   150.50948  376.23346  918.88416  476.55188 ]
  [346.45367  461.61664  147.78125   81.748604 880.62286 ]
  [546.5623   373.0645   392.1336   423.1727    14.433861]
  [997.1503   322.24213  956.8404   740.9524   446.47397 ]]

 [[414.4726   315.08804  591.89716  823.41455  160.06851 ]
  [853.7713   275.1404   662.5495   926.47955  406.62946 ]
  [489.11404  930.62177  977.2153   554.9443   378.6068  ]
  [213.96553   26.423573 837.02936  635.86774  565.0895  ]
  [717.6117   897.3037   631.1289   317.6154   158.79356 ]]

 [[176.6777   689.89215  156.95798  991.2535   936.74994 ]
  [778.82825  312.81174  970.456    900

Tensor indexing

In [14]:
tensor2=tf.constant([
    [1,2,3,4],
    [2,3,4,5],
    [1,2,4,5],
    [7,4,5,5]
])
print(tensor2[0:4,0:3])

tf.Tensor(
[[1 2 3]
 [2 3 4]
 [1 2 4]
 [7 4 5]], shape=(4, 3), dtype=int32)


In [15]:
tensor2=tf.constant([
    [1,2,3,4],
    [2,3,4,5],
    [1,2,4,5],
    [7,4,5,5]
])
print(tensor2[2,0:3])

tf.Tensor([1 2 4], shape=(3,), dtype=int32)


In [16]:
tensor3_abs=tf.abs(tensor3)
print(tensor3)

tf.Tensor(
[[[1 2 3 4]
  [2 3 4 5]]

 [[1 2 4 5]
  [7 4 5 5]]

 [[1 2 3 4]
  [2 3 4 5]]

 [[1 2 4 5]
  [7 4 5 5]]], shape=(4, 2, 4), dtype=int32)


Tensor Argmax

In [17]:
x_argmax=tf.constant([100,40,650,10000,30])
print(tf.math.argmax(x_argmax))

tf.Tensor(3, shape=(), dtype=int64)


In [20]:
x_argmin=tf.constant([100,40,650,10000,30])
print(tf.math.argmin(x_argmin))

tf.Tensor(4, shape=(), dtype=int64)


In [29]:
dimtens2_xargmax=tf.constant([
    [1,2,3,4],
    [2,3,4,5],
    [1,2,4,5],
    [7,4,5,5]
])
print(tf.math.argmax(dimtens2_xargmax,0))

tf.Tensor([3 3 3 1], shape=(4,), dtype=int64)


In [27]:
dimtens2_xargmin=tf.constant([
    [1,2,3,4],
    [2,3,4,5],
    [1,2,4,5],
    [7,4,5,5]
])
print(tf.math.argmin(dimtens2_xargmin,0))

tf.Tensor([0 0 0 0], shape=(4,), dtype=int64)


Tensor Reduce Sum

In [31]:
reduce_tensor_sum=tf.constant([
    [1,2,3,4],
    [2,3,4,5],
    [1,2,4,5],
    [7,4,5,5]
])
print(tf.math.reduce_sum(reduce_tensor_sum))

tf.Tensor(57, shape=(), dtype=int32)


In [32]:
reduce_tensor_max=tf.constant([
    [1,2,3,4],
    [2,3,4,5],
    [1,2,4,5],
    [7,4,5,5]
])
print(tf.math.reduce_max(reduce_tensor_max))

tf.Tensor(7, shape=(), dtype=int32)


In [33]:
reduce_tensor_min=tf.constant([
    [1,2,3,4],
    [2,3,4,5],
    [1,2,4,5],
    [7,4,5,5]
])
print(tf.math.reduce_min(reduce_tensor_min))

tf.Tensor(1, shape=(), dtype=int32)


Tensor Std

In [35]:
reduce_tensor_std=tf.constant([
    [1,2,3,4],
    [2,3,4,5],
    [1,2,4,5],
    [7,4,5,5]
],dtype=tf.float32)
print(tf.math.reduce_std(reduce_tensor_std))

tf.Tensor(1.6189792, shape=(), dtype=float32)


In [36]:
print(tf.math.top_k(reduce_tensor_max))

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[4],
       [5],
       [5],
       [7]], dtype=int32)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[3],
       [3],
       [3],
       [0]], dtype=int32)>)


In [37]:
x_mat=tf.constant([
    [1,2,3,4],
    [2,3,4,5],
    [1,2,4,5],
    [7,4,5,5]
])
y_mat=tf.constant([
    [1,2,3,4],
    [2,3,4,5],
    [1,2,4,5],
    [7,4,5,5]
])
print(tf.linalg.matmul(x_mat,y_mat))

tf.Tensor(
[[36 30 43 49]
 [47 41 59 68]
 [44 36 52 59]
 [55 56 82 98]], shape=(4, 4), dtype=int32)
