In [ ]:
import tensorflow as tf

One Dimensional Tensor



In [ ]:
onedimvar=tf.constant(4)
print(onedimvar)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
onedimvar=tf.constant([4,1,2,3,4])
onedimvar

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 1, 2, 3, 4], dtype=int32)>

Two Dimensional Tensor

In [ ]:
tensor2=tf.constant([
    [1,2,3,4],
    [2,3,4,5],
    [1,2,4,5],
    [7,4,5,5]
])
tensor2

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [1, 2, 4, 5],
       [7, 4, 5, 5]], dtype=int32)>

Three Dimensional Tensor

In [ ]:
tensor3=tf.constant([
    [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
     [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
])
tensor3

<tf.Tensor: shape=(4, 2, 4), dtype=int32, numpy=
array([[[1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[1, 2, 4, 5],
        [7, 4, 5, 5]],

       [[1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[1, 2, 4, 5],
        [7, 4, 5, 5]]], dtype=int32)>

In [ ]:
tensor4=tf.constant([
    [
    [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
     [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
],
    [
    [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
     [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
],
    [
    [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
     [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
],
    [
    [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
     [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
],
])
tensor4

<tf.Tensor: shape=(4, 4, 2, 4), dtype=int32, numpy=
array([[[[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]],

        [[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]]],


       [[[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]],

        [[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]]],


       [[[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]],

        [[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]]],


       [[[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]],

        [[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]]]], dtype=int32)>

Eye

In [ ]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=5,
    batch_shape=None,
    dtype=tf.dtypes.float32
)
eye_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [ ]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[5,9],
    dtype=tf.dtypes.float32
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  ...

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  ...

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0.

Fill

In [ ]:
fill_tensor=tf.fill(
    [3,3,3,3,3],11,name=None
)
print(fill_tensor)

tf.Tensor(
[[[[[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]]


  [[[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]]


  [[[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]]]



 [[[[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]]


  [[[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]]


  [[[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]]]



 [[[[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
   

One

In [ ]:
one_tensor=tf.ones(
    [5,5,15],
    dtype=tf.float32,
    name=None
)
print(one_tensor)

tf.Tensor(
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 

In [ ]:
ones_like_tensor=tf.ones_like(fill_tensor,
                              dtype=None,
                              name=None

)
print(ones_like_tensor)

tf.Tensor(
[[[[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]]



 [[[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]]



 [[[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 

Normal

In [ ]:
normal_tensor=tf.random.normal(
    [5,5,5],
     mean=0.0,
    stddev=1.0,

    dtype=tf.float32,
    seed=None,
    name=None
)
print(normal_tensor)

tf.Tensor(
[[[ 1.2955619   0.41108137  0.5594645  -0.37122017 -0.58284694]
  [-0.18728611 -1.0292662   1.8410156  -1.194428    0.73491925]
  [-0.9231957   1.261342   -0.18808205  2.1887462   0.6793526 ]
  [ 0.4694118  -0.96243     0.35383356  1.252862    0.0729489 ]
  [-0.34360415  0.23237492  0.21506375  1.6336627   0.26357195]]

 [[ 0.18597585  0.73183364 -0.5461216   0.60443574 -0.86033213]
  [ 0.59442115  0.7710726   1.7320478   0.30746192 -0.08902032]
  [ 0.8484413  -1.5177943   1.0318015   1.9788457   0.42360696]
  [ 0.479343   -1.2750363   1.2910953  -1.8143314  -0.65315   ]
  [ 0.00301888  1.3529757   2.0433207   0.4632176   0.07503856]]

 [[ 1.4020026   1.7565341   1.3903879   0.18061851  0.11766362]
  [-0.6643665  -0.5464858   0.5487967   0.25559583  1.3390641 ]
  [-0.75114393  1.5939139  -1.1987373   0.28753155  0.3861044 ]
  [-1.6121175   0.10549157  0.46273696 -0.00580877 -0.12736638]
  [-0.10995306 -1.3209903  -1.6544609  -0.8582162   1.3622787 ]]

 [[-0.55692804 -1.24206

In [ ]:
uniform_tensor=tf.random.uniform(
    [5,5,5],
    minval=0,
    maxval=1000,

    dtype=tf.float32,
    seed=None,
    name=None
)
print(uniform_tensor)

tf.Tensor(
[[[  9.449244  853.5315    882.64844   587.78894   397.4632   ]
  [916.7552    696.7403    249.31776   431.52786     1.6590357]
  [ 19.159676  694.479     260.21826   593.4817    112.45477  ]
  [456.2466    467.5703    958.5402    176.21518    10.291338 ]
  [128.85822   619.946     593.483     953.9275    648.37695  ]]

 [[290.43005   954.6884    105.4095    245.21089   191.09439  ]
  [527.09283   335.40308   651.54504   706.11084   778.1341   ]
  [901.84924   608.8941    465.0084    690.43884   738.81055  ]
  [850.1234    188.12048   584.4239    714.5916    216.31015  ]
  [483.17993   696.9167    949.35785   628.44226   937.4067   ]]

 [[969.2552    986.4129    579.8072    800.6967    555.289    ]
  [297.83167   377.0032    572.1608    235.67033   397.7257   ]
  [800.23883   544.38055   127.91848    59.98635    87.791565 ]
  [829.9004    195.54282   763.01086   496.95062   164.31784  ]
  [159.9667     83.98009   776.89087   899.1154    647.6917   ]]

 [[554.81805   848.4707

Tensor indexing

In [30]:
tensor2=tf.constant([
    [1,2,3,4],
    [2,3,4,5],
    [1,2,4,5],
    [7,4,5,5]
])
print(tensor2[0:4,0:3])

tf.Tensor(
[[1 2 3]
 [2 3 4]
 [1 2 4]
 [7 4 5]], shape=(4, 3), dtype=int32)


In [44]:
tensor2=tf.constant([
    [1,2,3,4],
    [2,3,4,5],
    [1,2,4,5],
    [7,4,5,5]
])
print(tensor2[2,0:3])

tf.Tensor([1 2 4], shape=(3,), dtype=int32)


In [46]:
tensor3_abs=tf.abs(tensor3)
print(tensor3)

tf.Tensor(
[[[1 2 3 4]
  [2 3 4 5]]

 [[1 2 4 5]
  [7 4 5 5]]

 [[1 2 3 4]
  [2 3 4 5]]

 [[1 2 4 5]
  [7 4 5 5]]], shape=(4, 2, 4), dtype=int32)
