In [2]:
import tensorflow as tf

One Dimensional Tensor



In [3]:
onedimvar=tf.constant(4)
print(onedimvar)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
onedimvar=tf.constant([4,1,2,3,4])
onedimvar

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 1, 2, 3, 4], dtype=int32)>

Two Dimensional Tensor

In [5]:
tensor2=tf.constant([
    [1,2,3,4],
    [2,3,4,5],
    [1,2,4,5],
    [7,4,5,5]
])
tensor2

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [1, 2, 4, 5],
       [7, 4, 5, 5]], dtype=int32)>

Three Dimensional Tensor

In [6]:
tensor3=tf.constant([
    [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
     [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
])
tensor3

<tf.Tensor: shape=(4, 2, 4), dtype=int32, numpy=
array([[[1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[1, 2, 4, 5],
        [7, 4, 5, 5]],

       [[1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[1, 2, 4, 5],
        [7, 4, 5, 5]]], dtype=int32)>

In [7]:
tensor4=tf.constant([
    [
    [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
     [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
],
    [
    [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
     [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
],
    [
    [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
     [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
],
    [
    [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
     [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
],
])
tensor4

<tf.Tensor: shape=(4, 4, 2, 4), dtype=int32, numpy=
array([[[[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]],

        [[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]]],


       [[[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]],

        [[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]]],


       [[[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]],

        [[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]]],


       [[[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]],

        [[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]]]], dtype=int32)>

Eye

In [10]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=5,
    batch_shape=None,
    dtype=tf.dtypes.float32
)
eye_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [12]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[5,9],
    dtype=tf.dtypes.float32
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  ...

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  ...

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0.

Fill

In [17]:
fill_tensor=tf.fill(
    [3,3,3,3,3],11,name=None
)
print(fill_tensor)

tf.Tensor(
[[[[[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]]


  [[[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]]


  [[[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]]]



 [[[[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]]


  [[[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]]


  [[[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]]]



 [[[[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
    [11 11 11]]

   [[11 11 11]
    [11 11 11]
   

One

In [20]:
one_tensor=tf.ones(
    [5,5,15],
    dtype=tf.float32,
    name=None
)
print(one_tensor)

tf.Tensor(
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 

In [22]:
ones_like_tensor=tf.ones_like(fill_tensor,
                              dtype=None,
                              name=None

)
print(ones_like_tensor)

tf.Tensor(
[[[[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]]



 [[[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]]



 [[[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 