In [ ]:
import tensorflow as tf

One Dimensional Tensor



In [ ]:
onedimvar=tf.constant(4)
print(onedimvar)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
onedimvar=tf.constant([4,1,2,3,4])
onedimvar

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 1, 2, 3, 4], dtype=int32)>

Two Dimensional Tensor

In [ ]:
tensor2=tf.constant([
    [1,2,3,4],
    [2,3,4,5],
    [1,2,4,5],
    [7,4,5,5]
])
tensor2

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [1, 2, 4, 5],
       [7, 4, 5, 5]], dtype=int32)>

Three Dimensional Tensor

In [ ]:
tensor3=tf.constant([
    [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
     [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
])
tensor3

<tf.Tensor: shape=(4, 2, 4), dtype=int32, numpy=
array([[[1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[1, 2, 4, 5],
        [7, 4, 5, 5]],

       [[1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[1, 2, 4, 5],
        [7, 4, 5, 5]]], dtype=int32)>

In [ ]:
tensor4=tf.constant([
    [
    [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
     [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
],
    [
    [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
     [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
],
    [
    [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
     [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
],
    [
    [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
     [[1,2,3,4],
    [2,3,4,5],],
    [[1,2,4,5],
    [7,4,5,5]],
],
])
tensor4

<tf.Tensor: shape=(4, 4, 2, 4), dtype=int32, numpy=
array([[[[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]],

        [[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]]],


       [[[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]],

        [[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]]],


       [[[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]],

        [[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]]],


       [[[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]],

        [[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[1, 2, 4, 5],
         [7, 4, 5, 5]]]], dtype=int32)>